#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# hook to enforce that current branch is up-to-date with latest
# changes from master before committing

# put me in .git/hooks and make me executable

# the output of rev-list in the following test will be empty if there
# are no commits in master that aren't in the current branch

if [ ! -z $(git rev-list ..master) ]; then
    echo "abandoning commit"
    echo "please merge from master and try again"
    exit 1
fi
